######## ##          ###    ##     ## ########  ######  ########    ###    ######## ########
##       ##         ## ##   ###   ### ##       ##    ##    ##      ## ##   ##       ##
##       ##        ##   ##  #### #### ##       ##          ##     ##   ##  ##       ##
######   ##       ##     ## ## ### ## ######    ######     ##    ##     ## ######   ######
##       ##       ######### ##     ## ##             ##    ##    ######### ##       ##
##       ##       ##     ## ##     ## ##       ##    ##    ##    ##     ## ##       ##
##       ######## ##     ## ##     ## ########  ######     ##    ##     ## ##       ##
name: FlameStaff
version: ${project.version}
main: com.github.firewolf8385.flamestaff.FlameStaff
api-version: 1.16
author: firewolf8385
permission-message: &noperms "§c§l(§7§l!§c§l) §cYou do not have access to that command."

 #####
#     #  ####  #    # #    #   ##   #    # #####   ####
#       #    # ##  ## ##  ##  #  #  ##   # #    # #
#       #    # # ## # # ## # #    # # #  # #    #  ####
#       #    # #    # #    # ###### #  # # #    #      #
#     # #    # #    # #    # #    # #   ## #    # #    #
 #####   ####  #    # #    # #    # #    # #####   ####
commands:
  ecsee:
    description: Open a player''s enderchest.
    permission: flamestaff.ecsee
    permission-message: *noperms
  commandspy:
    description: Spy on other''s commands.
    aliases: [cmdspy]
    permission: flamestaff.commandspy
    permission-message: *noperms
  invisibile:
    description: Hide yourself ingame without leaving tab.
    aliases: [invis]
    permission: flamestaff.invisible
    permission-message: *noperms
  invsee:
    description: View another player''s inventory.
    permission: flamestaff.invsee
    permission-message: *noperms
  vanish:
    description: Hide yourself ingame
    aliases: [v]
    permission: flamestaff.vanish
    permission-message: *noperms


######
#     # ###### #####  #    # #  ####   ####  #  ####  #    #  ####
#     # #      #    # ##  ## # #      #      # #    # ##   # #
######  #####  #    # # ## # #  ####   ####  # #    # # #  #  ####
#       #      #####  #    # #      #      # # #    # #  # #      #
#       #      #   #  #    # # #    # #    # # #    # #   ## #    #
#       ###### #    # #    # #  ####   ####  #  ####  #    #  ####
permissions:
  flamestaff.*:
    description: Give access to all flamestaff commands.
    default: false
    children:
      flamestaff.all: true
  flamestaff.all:
    description: Give access to all flamestaff commands.
    default: false
    children:
      flamestaff.commandspy: true
      flamestaff.commandspy.exempt: true
      flamestaff.ecsee: true
      flamestaff.invisible: true
      flamestaff.invsee: true
      flamestaff.vanish: true
  flamestaff.commandspy:
    description: Spy on other''s commands.
    default: op
  flamestaff.commandspy.exempt:
    description: Makes you exempt from command spy.
    default: false
  flamestaff.ecsee:
    description: View a player''s enderchest.
    default: op
  flamestaff.invisible:
    description: Hide yourself ingame without leaving tab.
    default: op
  flamestaff.invsee:
    description: View another player''s inventory.
    default: op
  flamestaff.vanish:
    description: Hide yourself ingame
    default: op